### PR TITLE
Extracting logic to separate module

### PR DESCRIPTION
**Pull request by liorgreenb**
Extracting the main logic to a module for using in custom CLIs

### CODE REVIEW

**Review by kribblo — COMMENTED** [review]
Maybe I'm missing some subtle thing, but what's with the braces {} around `{getLinked}`? Other than that, seems like a very useful addition I'd be happy to merge. Or even with them, if there's a reason. :)

**Comment by liorgreenb** [comment]
It just makes it a non default import, in case the module has any other
exports in the future, i can make it a default if you prefer.

**Comment by kribblo** [comment]
Oh, yeah, thanks! Just didn't know about it, that's fine. :)

**Comment by liorgreenb** [comment]
Thanks and sorry for the error you fixed.
Can you publish this on npm?

**Comment by kribblo** [comment]
It's published

**Pull request merged**
